name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
  # Run weekly, so that the baseline AppMap artifact does not expire.
  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: read
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        pip install Flask-WTF 

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python 3.x version

    - name: Install dependencies (for tests, if needed)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # You can also add any additional dependencies required for testing here

    - name: Run tests
      run: |
        python3 tests.py  # Use python3 to run tests

    - name: Save AppMaps
      uses: actions/cache/save@v3
      if: always()
      with:
        path: ./tmp/appmap
        key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

  appmap-analysis:
    if: always()
    needs: [test] 
    permissions:
      actions: read
      contents: read
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run AppMap Analysis
      uses: getappmap/analyze-action@v1
    

