name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
  # Run weekly, so that the baseline AppMap artifact does not expire.
  schedule:
    - cron: '0 0 * * 0'

permissions:
  actions: read
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        # Checkout pull request head so that a commit can be made
        ref: ${{ github.event.pull_request.head.ref }}


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python 3.x version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  
        pip install Flask-WTF 
    
    # Begin install-action snippet
    - name: Install AppMap tools
      id: install-appmap
      uses: getappmap/install-action@v1
      with:
        project-type: pipenv
        build-patch-file: false
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        add: './REPOADMINS.md'
        default_author: github_actions
    # End install-action snippet

    - name: Run tests
      run: |
        python3 tests.py  # Use python3 to run tests

    - name: Archive AppMaps
      uses: getappmap/archive-action@v1
      with:
        revision: ${{ github.event.pull_request.base.sha }}